### ISSUE TITLE
Setup corrupts ssh settings

### ISSUE THREAD

**Issue by springjools** [geerlingguy/drupal-pi#44]
Running the setup on remote pi with ssh is dangerous, because it can lock user out of the pi entirely, because of tampering with ssh config. 

Needs a warning or better remote this unwanted behaviour.

**Comment by geerlingguy** [comment]
@springjools - All the security-related settings are managed by my `geerlingguy.security` role (see https://github.com/geerlingguy/ansible-role-security).

You can override settings like the following in your config file:

```yaml
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
```

Note that this playbook is meant to configure a dedicated Pi, and is not meant to be an "add on stuff to an existing Pi" type of playbook. I routinely wipe out and rebuild my Pis from scratch, re-flashing Raspbian lite to the microSD cards.

Any important data on the Pi itself is backed up nightly, to make sure any problems can be quickly remedied by wiping the Pi then re-installing everything using this playbook.
